[package]
name = "codex_usage"
version = "0.1.0"
edition = "2021"
authors = ["Wei Lee <mai@mai0313.com>"]
description = "Codex 與 Claude Code 遙測/使用紀錄解析器，彙總 JSONL 事件為 CodeAnalysis 結果。"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/<owner>/codex-usage"
repository = "https://github.com/<owner>/codex-usage"

[dependencies]

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
