// Main library modules
pub mod analysis;
pub mod cli;
pub mod models;
pub mod pricing;
pub mod update;
pub mod usage;
pub mod utils;

// Re-export commonly used types
pub use analysis::analyzer::analyze_jsonl_file;
pub use models::*;
pub use usage::calculator::get_usage_from_directories;

/// Version information
/// This version is dynamically generated by build.rs to include git information
pub const VERSION: &str = env!("BUILD_VERSION");
pub const PKG_NAME: &str = env!("CARGO_PKG_NAME");
pub const PKG_DESCRIPTION: &str = env!("CARGO_PKG_DESCRIPTION");

/// Rust version used at build time
pub const RUST_VERSION: &str = env!("BUILD_RUST_VERSION");

/// Cargo version used at build time
pub const CARGO_VERSION: &str = env!("BUILD_CARGO_VERSION");

/// Get version info struct
pub fn get_version_info() -> VersionInfo {
    VersionInfo {
        version: VERSION.to_string(),
        rust_version: RUST_VERSION.to_string(),
        cargo_version: CARGO_VERSION.to_string(),
    }
}

/// Version information structure
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct VersionInfo {
    pub version: String,
    pub rust_version: String,
    pub cargo_version: String,
}
